### ISSUE TITLE
고객은 식권 구매 여부를 선택할 수 있습니다.

### ISSUE THREAD

**Issue by ooANAoo** [ssg-java3-240304/oop2-TenTen-Cafeteria#31]
## 🌈 Success criteria
        
1. 식권 구매 안내 문구를 출력한다.
1. 구매 선택 시 Kiosk의 buyCoupon 호출
2. 구매 안함 선택 시 Kiosk의 useCoupon 호출
 - 식권 0개일 시 구매 안내 문구 자동 출력
        
## 👷To-do
        

        
- [ ]  안내 문구 작성
- [ ]  Kiosk의 buyCoupon() 호출
- [ ]  Kiosk의 useCoupon() 호출
