### ISSUE TITLE
- MainController는 사용자에게 오늘의 점심 메뉴나 일주일 식단표를 보여줍니다.

### ISSUE THREAD

**Issue by ooANAoo** [ssg-java3-240304/oop2-TenTen-Cafeteria#37]
## 🌈 Success criteria
        
 1. MainController는 Kiosk에게 오늘의 점심 메뉴를 보여주도록 요청합니다.
 2. MainController는 Kiosk에게 일주일 식단표를 보여주도록 요청합니다.
        
## 👷To-do
        
- [ ]  showWeekMenu():void 메소드 생성
- [ ]  Kiosk의 displayDailyMenu() 호출 - 오늘의 점심 메뉴
- [ ]  Kiosk의 displayWeekMenu() 호출 - 일주일 식단표
